apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockchain-lottery-indexer.fullname" . }}-secrets
  labels:
    {{- include "blockchain-lottery-indexer.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ default "replace-in-production" .Values.secrets.jwtSecret | quote }}
  mysql-password: {{ default "root" .Values.secrets.mysqlPassword | quote }}
